apiVersion: v1
kind: Service
metadata:
  labels:
    app: proms
  name: proms-9090
spec:
  externalIPs:
  - 172.29.0.12
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: proms
