apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc-nfs
  namespace: gitea
spec:
  storageClassName: gitea-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
