apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
  labels:
    app: ldap
spec:
  replicas: 1
  selector:
   matchLabels:
    app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
#      nodeSelector:
#        app: ldap
      containers:
        - name: ldap
          image: osixia/openldap:1.4.0
          args : [ "--copy-service" ]
          volumeMounts:
            - name: ldif-bootstrap
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
              subPath: 50-bootstrap.ldif

          ports:
            - containerPort: 389
              name: openldap
            - containerPort: 636
              name: ldpas
          env:
            - name: LDAP_LOG_LEVEL
              value: "256"
            - name: LDAP_ADMIN_PASSWORD
              value: "bigred"
            - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
              value: "false"

      volumes:
        - name: ldif-bootstrap
          persistentVolumeClaim:
            claimName: ldap-pvc-nfs
#          hostPath:
#            path: /data/ldap/bootstrap/init.ldif
