apiVersion: v1
kind: PersistentVolume
metadata:
  name: ldap-pv-nfs
  labels:
    app: ldap
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ldap-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume2/NFS/ldap
    server: 192.168.2.201
