apiVersion: v1
kind: Service
metadata:
  labels:
    app: ldap
  name: ldap-service
spec:
  externalIPs:
  - 172.29.0.12
  ports:
    - protocol: TCP
      port: 389
      targetPort: 389
  selector:
    app: ldap
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ldap
  name: ldaps-service-636
spec:
  externalIPs:
  - 172.29.0.12
  ports:
    - protocol: TCP
      port: 636
      targetPort: 636
  selector:
    app: ldap
