apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpldapadmin
  name: phpldapadmin-service-80
spec:
  externalIPs:
  - 172.29.0.12
  ports:
    - protocol: TCP
      port: 8899
      targetPort: 80
  selector:
    app: phpldapadmin
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpldapadmin
  name: phpldapadmin-service-443
spec:
  externalIPs:
  - 172.29.0.12
  ports:
    - protocol: TCP
      port: 4443
      targetPort: 443
  selector:
    app: phpldapadmin
