apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-nfs
  namespace: jenkins
spec:
  storageClassName: jenkins-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
