apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
  namespace: gitea
spec:
  storageClassName: gitea
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
