apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  namespace: gitea
  labels:
    app: gitea
spec:
  externalIPs:
    - 172.29.0.14
  ports:
    - name: gitea-http
      port: 3000
    - name: gitea-ssh
      port: 30022
      targetPort: 22
  selector:
    app: gitea

